spring.datasource.url=jdbc:postgresql://localhost:5432/ai-edtech
spring.datasource.username=ilya
spring.datasource.password=edtech

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
server.port=8080
