-- V1__init.sql
-- MVP schema (PostgreSQL + Flyway)
-- Notes:
-- - IDs are UUIDs generated by the application
-- - trace_id is TEXT to support any correlation/trace id format (UUID, OTel, etc.)
-- - jsonb stores typed structures (criteria, grade schemes, results)

-- =========================
-- 1) RUBRICS
-- =========================
CREATE TABLE rubrics (
                         id           uuid        PRIMARY KEY,
                         name         text        NOT NULL,
                         criteria     jsonb       NOT NULL,
                         grade_scheme jsonb       NOT NULL,
                         created_by   text        NOT NULL,
                         created_at   timestamptz NOT NULL DEFAULT now(),
                         updated_at   timestamptz NOT NULL DEFAULT now()
);

-- =========================
-- 2) SUBMISSIONS
-- =========================
CREATE TABLE submissions (
                             id         uuid        PRIMARY KEY,
                             rubric_id  uuid        NOT NULL,
                             student_id text        NOT NULL,
                             text       text        NOT NULL, -- sensitive data, do NOT log
                             created_at timestamptz NOT NULL DEFAULT now(),
                             CONSTRAINT fk_submissions_rubrics
                                 FOREIGN KEY (rubric_id) REFERENCES rubrics(id)
);

CREATE INDEX idx_submissions_rubric_id  ON submissions (rubric_id);
CREATE INDEX idx_submissions_student_id ON submissions (student_id);

-- =========================
-- 3) EVALUATION JOBS
-- =========================
CREATE TABLE evaluation_jobs (
                                 id               uuid        PRIMARY KEY,
                                 submission_id    uuid        NOT NULL,
                                 status           text        NOT NULL,
                                 attempts         integer     NOT NULL DEFAULT 0,
                                 last_error_code  text        NULL,
                                 last_error_message text      NULL,
                                 trace_id         text        NULL,
                                 created_at       timestamptz NOT NULL DEFAULT now(),
                                 updated_at       timestamptz NOT NULL DEFAULT now(),
                                 started_at       timestamptz NULL,
                                 finished_at      timestamptz NULL,

                                 CONSTRAINT fk_jobs_submissions
                                     FOREIGN KEY (submission_id) REFERENCES submissions(id),

                                 CONSTRAINT chk_jobs_status
                                     CHECK (status IN ('QUEUED','RUNNING','DONE','FAILED')),

                                 CONSTRAINT chk_jobs_attempts_nonneg
                                     CHECK (attempts >= 0)
);

CREATE INDEX idx_jobs_submission_id        ON evaluation_jobs (submission_id);
CREATE INDEX idx_jobs_submission_status    ON evaluation_jobs (submission_id, status);
CREATE INDEX idx_jobs_status_updated_at    ON evaluation_jobs (status, updated_at);

-- Hard guarantee: max 1 ACTIVE job per submission (protects from double-click / races)
CREATE UNIQUE INDEX uq_jobs_active_per_submission
    ON evaluation_jobs (submission_id)
    WHERE status IN ('QUEUED','RUNNING');

-- =========================
-- 4) AI RESULTS
-- =========================
CREATE TABLE ai_results (
                            id                   uuid        PRIMARY KEY,
                            submission_id        uuid        NOT NULL,
                            job_id               uuid        NOT NULL,
                            criteria_results     jsonb       NOT NULL,
                            total_score_normalized numeric(5,2) NOT NULL,
                            model                text        NULL,
                            prompt_version       text        NULL,
                            trace_id             text        NULL,
                            created_at           timestamptz NOT NULL DEFAULT now(),

                            CONSTRAINT fk_ai_results_submission
                                FOREIGN KEY (submission_id) REFERENCES submissions(id),

                            CONSTRAINT fk_ai_results_job
                                FOREIGN KEY (job_id) REFERENCES evaluation_jobs(id),

                            CONSTRAINT uq_ai_results_submission
                                UNIQUE (submission_id),

                            CONSTRAINT chk_ai_results_total
                                CHECK (total_score_normalized >= 0 AND total_score_normalized <= 100)
);

CREATE INDEX idx_ai_results_job_id ON ai_results (job_id);

-- =========================
-- 5) TEACHER DECISIONS
-- =========================
CREATE TABLE teacher_decisions (
                                   id                   uuid        PRIMARY KEY,
                                   submission_id        uuid        NOT NULL,
                                   ai_result_id         uuid        NULL,
                                   mode                 text        NOT NULL,
                                   criteria_results     jsonb       NOT NULL,
                                   comment              text        NULL,
                                   total_score_normalized numeric(5,2) NOT NULL,
                                   final_grade          jsonb       NOT NULL,
                                   decided_by           text        NOT NULL,
                                   decided_at           timestamptz NOT NULL DEFAULT now(),

                                   CONSTRAINT fk_decisions_submission
                                       FOREIGN KEY (submission_id) REFERENCES submissions(id),

                                   CONSTRAINT fk_decisions_ai_result
                                       FOREIGN KEY (ai_result_id) REFERENCES ai_results(id),

                                   CONSTRAINT uq_decisions_submission
                                       UNIQUE (submission_id),

                                   CONSTRAINT chk_decisions_mode
                                       CHECK (mode IN ('ACCEPT_AI','OVERRIDE')),

                                   CONSTRAINT chk_decisions_total
                                       CHECK (total_score_normalized >= 0 AND total_score_normalized <= 100),

    -- Correctness rule:
    -- ACCEPT_AI is impossible without an AI result reference
                                   CONSTRAINT chk_decisions_accept_ai_requires_ai_result
                                       CHECK (mode <> 'ACCEPT_AI' OR ai_result_id IS NOT NULL)
);

CREATE INDEX idx_decisions_decided_by ON teacher_decisions (decided_by);